modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="you_can_explain_nothing"
version="1.2.0"
displayName="You Can Explain Nothing."
credits="by FXGstudio & RESPECTIFUL_UR"
displayURL="https://mcbbs.net"
authors="FXGstudio, RESPECTIFUL_UR"

[[dependencies.you_can_explain_nothing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




