modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="you_can_explain_nothing"
version="1.3.2"
displayName="You Can Explain Nothing."
credits="There's nothing here!"
displayURL="https://mcbbs.net"
authors="FXGstudio"
description='''
nope.
'''

[[dependencies.you_can_explain_nothing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




